### PR TITLE
Support to configure localization of results file

### PR DESCRIPTION
**Pull request by soleverxu**

### CODE REVIEW

**Review by tamar-moses — CHANGES_REQUESTED** [review]
Regarding the readme: 
1. runType (Can we rename to runFrom?)
2. "[Mandatory] Specify the test assets location type."
Change to: The test asset location type. (in singular, like apple tree. and no "Specify", like in the other parameters)
3. "Alm for UFT GUI/API tests stored on an Micro Focus Application Lifecycle Management (ALM) server." - "a", not "an". before Micro Focus...
4. Why do we need the timestamp paramter? why would we want to provide the time and not use the current local time?
5. resultFileLangTag 
     a. unclear parameter name. Does this affect only the demical point representation?
     b. Why enable blank and default and invariant. just use one, no?
     same question about Auto/System

**Comment by soleverxu** [comment]
Please see my comments below. Thanks.

> Regarding the readme:
> 
> 1. runType (Can we rename to runFrom?)
- Currently Jenkins plugin uses `runType` as the most important parameter so we have to use this parameter. We may consider to use parameters `runFrom` (for standalone tool) and `runType` as the alias (for plugins). 
> 2. "[Mandatory] Specify the test assets location type."
>    Change to: The test asset location type. (in singular, like apple tree. and no "Specify", like in the other parameters)
- Done in the last commit
> 3. "Alm for UFT GUI/API tests stored on an Micro Focus Application Lifecycle Management (ALM) server." - "a", not "an". before Micro Focus...
- Done in the last commit
> 4. Why do we need the timestamp paramter? why would we want to provide the time and not use the current local time?
- Good question, this parameter is meaningless for standalone tool. Removed in the last commit.
> 5. resultFileLangTag
>    a. unclear parameter name. Does this affect only the demical point representation?
- This setting shall affect the number, data and time formats as the configuration in Windows Region settings. Any suggestions of this parameter name?
>    b. Why enable blank and default and invariant. just use one, no?
- Good point. Only one value `Default` is mentioned and changes were made in the last commit.
>    same question about Auto/System
- Only one value `System` is mentioned - changed in the last commit.

**Comment by tamar-moses** [comment]
1.	Thanks for the explanations. 
2.	runType can stay. 
3.	resultFileLangTag: We need to mention “tag” less. This definition is about the language to use. The tag just happens to be the letters that express the language. 
Also, I think you meant date and not data.
So here is my suggestion for the name and description: 
Name suggestion for parameter: resultFormatLanguage

(Optional) The language ~~tag~~ used to format numbers, dates, and times in the test results summary file. For example, the number 12.34 is generated as is in English (language tag en-US) while it is 12,34 in German (language tag de-DE). The value can be either a valid language tag or one of the case-insensitive constants.
**Tamar: What is the difference between a valid language tag and a case-insensitive constant?**

The default language is English.
~~If the value is Default or it is not set, the content is always generated in the neutral English language.~~

If the value is System, the application will automatically detect the language used in the system and use that language to do for localization. ~~In most cases, the language tag is same as the display language configured in the system.~~

**Tamar: The following paragraph needs to be clarified once I understand the difference between language tag and a case-insensitive constant**
The value can also be one of the valid case-insensitive language tag names such as en-US, de-DE and so on. For a list of predefined language tag names on Windows systems, see the **Language tag** column in the list of language/region names supported by Windows. The names follow the standard defined by BCP 47. In addition, starting with **Windows 10**, name can be any valid BCP-47 language tag.
**Tamar: The BCP-47link is not helpful enough. I could not easily find the list of languages. **

**Review by tamar-moses — CHANGES_REQUESTED** [review]
Looks good
I need an explanation about the difference between language tag and a case-insensitive constants
Thanks

**Comment by soleverxu** [comment]
1. The valid language tag is obviously the tag name like `en-US` and `de-DE`, and the case-insensitive constant I meant is the pre-defined string like `Default` and `System`. However, we have separated paragraphs that describe the details of `Default`, `System`, and the language tags, the sentence "_The value can be either a valid language tag or one of the case-insensitive constants._" is not necessary at all, so I removed the sentence in the last commit.
2. The paragraph "_For a list of predefined language tag names on Windows systems, see the Language tag column in the list of language/region names supported by Windows. The names follow the standard defined by BCP 47. In addition, starting with Windows 10, name can be any valid BCP-47 language tag._" comes from the Microsoft documentation and I just pasted it here. Reference: https://docs.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.createspecificculture?view=net-5.0#remarks

**Review by tamar-moses — CHANGES_REQUESTED** [review]
OK now :-)
Expect it looks like I missed marking one strikethrough. 
Need to change this 
"the application will automatically detect the language used in the system and use that language ~~to do~~ for localization."
to this
"the application will automatically detect the language used in the system and use that language for localization."

**Review by tamar-moses — APPROVED** [review]

**Pull request merged**
