### PR TITLE
Add parameter to populate test name only in results summary file

### PR DESCRIPTION
**Pull request by soleverxu**

### CODE REVIEW

**Review by tamar-moses — CHANGES_REQUESTED** [review]
I would try to rewrite this more simply:
resultTestNameOnly
(Optional) Indicates whether the test results summary file should include only test names for UFT One tests, rather than full paths. The LoadRunner tests are not affected. Default = false.

For example, by default the test results summary file includes the full path of the UFT One test. For example: <testcase name="C:\tests\GUITest1".
When this parameter is set to true, the results show the test name only: <testcase name="GUITest1".

**Comment by soleverxu** [comment]
The README doc is updated accordingly.

**Review by tamar-moses — COMMENTED** [review]
I can only approve the readme part...
Also, I see I left too many "For example" :-)
THis this better: 
~~For example, b~~By default the test results summary file includes the full path of the UFT One test. For example: <testcase name="C:\tests\GUITest1".
When this parameter is set to true, the results show the test name only: <testcase name="GUITest1".

**Comment by soleverxu** [comment]
Doc is updated. Thank you for reviewing the doc 👍

**Pull request merged**
