### PR TITLE
DEF-685004 & DEF-719010 & DEF-735138 #77  --> fix / improve ALM validations, add error messages, handle duplicate TestSet names, etc..

### PR DESCRIPTION
**Pull request by dorin7bogdan**
685004 [ADO][ALM] SSO login cannot be used for ALM server >= 15.5
719010 [ADO][ALM] Odd error displayed when TS is specified only by name

### CODE REVIEW

**Review by soleverxu — APPROVED** [review]

**Comment by soleverxu** [comment]
Please add more meaningful description when merging the PR rather than defect ID.

**Comment by dorin7bogdan** [comment]
> Please add more meaningful description when merging the PR rather than defect ID.
Hi Solever, I cannot merge yet the PR, maybe need some permission?

**Comment by soleverxu** [comment]
I can do the merge for you. Please provide the details of this PR as this description would be used as `What's New` when publishing the new release. Thanks,

**Comment by dorin7bogdan** [comment]
Fix / improve ALM validations, handle invalid or duplicate TestSet names, added 3 new error messages:
* The parameter 'almApiKeySecretBasicAuth' or 'almApiKeySecret' is required to run a test from ALM with SSO enabled.
* The parameters 'almApiKeySecretBasicAuth' and 'almApiKeySecret' cannot be used simultaneously when run a test from ALM with SSO enabled.
* Missing or invalid Test Set path.

ALM validation errors will be sent to STDERR stream, used by ADM-TFS-Extension's error detection mechanism.
The property 'almApiKeySecret' should not be set manually, it is comming from ADM-TFS-Extension as encrypted.
The TestSet name must contain the full path (the parent folder "Root" is still optional).
The standalone identifier "\\" is no longer a valid TestSet value.

**Pull request merged**
